### ISSUE TITLE
Plugin contain a commercial product file

### ISSUE THREAD

**Issue by creinke** [cucumber/cucumber-eclipse#100]
We are looking to use the Cucumber Eclipse Plugin in our organization.  However, when we looked into the plugin to determine if any commercial licensed software was being included, we found the GherkinReconcilingStrategy.java file from Squish.  The license agreement on this file is as follows:  

 * This file is part of Squish.
 *
 * Licensees holding a valid Squish License Agreement may use this
 * file in accordance with the Squish License Agreement provided with
 * the Software.

Given that we do not have such an agreement, we will not be able to use the plugin unless this file and binary is replaced with an open source equivalent.  Our organization is very strict in that regard.  

Was it your intention to include a commercial/licensed file in this plugin or was that an oversight on your part.  Please advise.  

Regards,

**Comment by ilanpillemer** [comment]
He was told to remove that.

How frustrating. He claimed he had accidentally put that in there.

This is an oversight. The developer who did that said his IDE automatically
generated that and he would remove it. :(

**Comment by ilanpillemer** [comment]
@apaku can you please remove the copyright blurb on this page, or otherwise I am going to have to remove this code from the project. Thanks!

**Comment by apaku** [comment]
Hi,

I'm terribly sorry I must have lost track about the request. Since we've stopped using cucumber-eclipse I don't have a clone anymore so can't file a pull-request. I've created a commit locally, the git format-patch is below. Alternatively, afaik (based on my experience within KDE) its sufficient if I explicitly tell you that changing the license of the files I touched is fine with me. So don't hesitate to just drop the header yourself, as I said it was an accident and my employer claims no rights on the code (there's hardly any logic to copyright in that file anyway).

From 89360724341b253699a1d90805e02b303c6ded60 Mon Sep 17 00:00:00 2001
From: Andreas Pakulat <apaku@gmx.de>
Date: Sat, 14 Feb 2015 22:23:13 +0100
Subject: [PATCH] Remove unintended commercial copyright notice.

---
 .../editor/editors/GherkinReconcilingStrategy.java    | 19 -------------------
 1 file changed, 19 deletions(-)

diff --git a/cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinReconcilingStrategy.java b/cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinReconcilingStrategy.java
index 9bb9b9e..fccfd57 100644
--- a/cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinReconcilingStrategy.java
+++ b/cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinReconcilingStrategy.java
@@ -1,22 +1,3 @@
-/**
- * Copyright (C) 2014 froglogic GmbH.
- * All rights reserved.
- *
- * This file is part of Squish.
- *
- * Licensees holding a valid Squish License Agreement may use this
- * file in accordance with the Squish License Agreement provided with
- * the Software.
- *
- * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
- * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
- *
- * See the LICENSE file in the toplevel directory of this package.
- *
- * Contact contact@froglogic.com if any conditions of this licensing are
- * not clear to you.
- *
- */
 package cucumber.eclipse.editor.editors;
 
 import gherkin.formatter.Formatter;
-- 
2.1.4

**Comment by ilanpillemer** [comment]
You could just delete the copyright online directly.

**Comment by ilanpillemer** [comment]
@apaku , will you be able to just do the update online in github? Should just take 5 seconds.
