### ISSUE TITLE
Incorrectly matching private methods

### ISSUE THREAD

**Issue by DanyalBurke** [cucumber/cucumber-eclipse#168]
If I create a private method like this:

```
@Given("^I do a step$")
private void doStep() { }
```

The features UI will show the step as matching (not yellow) but the Cucumber test runner won't consider the step.

**Comment by qvdk** [comment]
This bug should be resolved with the replacement of the AST parser by cucumber-jvm itself.
Since the plugin currently parse itself Java sources, it does the same job than cucumber-jvm. But, it should completely delegate this task to cucumber-jvm.

This issue should be addressed in the same time as the upgrade of cucumber-jvm.

**Comment by laeubi** [comment]
the 2.x version uses cucumber-jvm to parse steps, please retest if you are still seeng the issue there
