### ISSUE TITLE
plugin not recognizing constants?

### ISSUE THREAD

**Issue by stephzilla** [cucumber/cucumber-eclipse#171]
We are experiencing an issue where the Eclipse Cucumber plugin is not recognizing our feature steps if we've set it as a constant instead of a string.

Quick Example:

> Constant: @Given(PageConstants.Step.I_NAVIGATE_TO_THE + MAIN_PAGE + "$")
> vs.
> String: @When("I scroll to(?: the)? (.*)$")

Has anyone else had this issue? Did you find a fix?

**Comment by jgelon** [comment]
This is a feature I am also looking for. The step is recognized by the compiler when running, but not in the plugin.
I have seen some changes on the stepmatcher by @mplord, are you able to integrate this feature aswell?

**Comment by mplord** [comment]
Apologies it took me a while to realise this might be a request for me to perhaps provide a solution to this issue. If that's correct, that's fine - but I expect this would be very difficult to do.

If you imagine the step-matching plugin works through reflection on the code, it is a static determination of what matches without the code actually running or having been compiled.

Your constant expression evaluations are not knowable without actually a) running the code, or b) attempting to derive this from further inspection of the code - how would the plugin find your constant definitions, and interpret the concatenations etc - it would need to 'execute' the expressions first.

Once your code is running, all this is resolved and the annotations receive the final string, that's why cucumber can match the steps during execution.

So unfortunately a) isn't an option in the static ide, and b) seems like a very far-fetched option.
Apologies I don't think anyone will be able to solve this one anytime soon.
I might be wrong - is there an example of any other plugin which has solved this?

On a side note, what do you gain by putting parts of the regexp in constants? You're creating a new level of management which people have to learn and understand. Changing one constant still requires you to change all the steps in your feature files. Writing a new step requires you to recall the constants structure and location. I can't see the value add here over just having the regexps clearly declared?

**Comment by laeubi** [comment]
The new 2.x version uses cucumber to parse the steps and will support constants
