### ISSUE TITLE
List steps containing the word after the step keyword

### ISSUE THREAD

**Issue by pandug** [cucumber/cucumber-eclipse#205]
Please add feature to populate the matched predefined steps that contains the next word after step-keyword when trying to find the steps by pressing [CTRL]+[SPACE]. This will provide an easy way to search the steps created by functionality and avoid creating redundant steps.

**Comment by girijant** [comment]
Hello,
Content Assistance feature for step definition is already implemented.Please go though below reference  for your understanding: https://github.com/cucumber/cucumber-eclipse/wiki/Content-Assistance-for-feature-file

Hope this will help you.If you have any query or any enhancement please let me know.

Thanks,
Girija

**Comment by pandug** [comment]
Hi Girija,

Thanks for your response. I do not find the details in the wiki to search for steps containing specific word or by stepdefinition filename. 

Could you please let me know how I can perform the above search?

Thank you.

**Comment by girijant** [comment]
Please go through below rules as I specified on above wiki page : 
b. Rules for step Assistance :

- Populates all/search based predefined steps proposal by pressing '[Ctrl]+[Space]' keys.

- New line MUST be starts with a valid Step-Keyword.

- If Next word is blank : Populates all predefined steps

- If Next word starts with any matched step : Populates only matched predefined steps

- If Next word starts with any unmatched step : Populates 'No Proposals'

Apply above rules and cross verify those on your eclipse editor.Make sure you have installed proper plugin with correct version from here.Else uninstall older plugin, restart eclipse, close all feature files opened in your editor and reinstall plugin.
If your need doesn't satisfy above rule then have to improvise content-assistance feature.

Thanks,
~Girija

**Comment by pandug** [comment]
Hi Girija,

I have installed the latest version and applied all the rules for step assistance. 
But do not find the below features:
 - search steps by stepdefinition filename 
Ex: When searched with LoginSteps.java, all the steps defined in the class to be populated

 - search for steps that contains specific word instead of starts-with
Ex: When searched with "login" word, all the pre-defined steps containing the word "login" to be populated
          clicks on login button
          login should fail with message

Above features inclusion will help a lot  when there are hundreds of steps created in automation suite and trying to build scenarios using the existing steps for new features automation.

Thank you.

**Comment by girijant** [comment]
Here are my comments and please clarify your need as below : 
1.search steps by stepdefinition filename
Ex: When searched with LoginSteps.java, all the steps defined in the class to be populated.
- This feature should not be part of content assistance feature.Because while writing a feature file,user only bothers about predefined steps instead of .java file.Our content-assistance feature also supports to populate Steps with java-file name.
- If user already know the java file contains predefined steps then what's the need of using content-assistance ???
- As feature file only allows to write steps then Why user will type 'login.java' in a feature file to populate all the steps ??

2.search for steps that contains specific word instead of starts-with
Ex: When searched with "login" word, all the pre-defined steps containing the word "login" to be populated
- This is an improvement which can be fixed quickly.Knowingly I skipped this as I was waiting for the user input.

Thanks,
~Girija

**Comment by pandug** [comment]
Hi Girija,

Feature for searching steps containing a word will suffice. In our project, stepdefinitions files are organized by functionality. On second thought, search steps by stepdefinition filename is not required if search steps containing specific word(s) feature is implemented.  It is only useful if user doesn't want to access java file and view the list of steps implemented for a functionality in a file. I feel it will not be used much.

Thank you.

**Comment by girijant** [comment]
@pandug, 
Issue is got fixed and available in latest plugin version '0.0.18' with below summary:
- Fixed for duplicate step definitions
- Fixed for content-assistance with an improvised feature i.e. Steps can be populated based on both starts-with and contains with any words. 

Please update plugin with latest version and let me know if any issue. 

Thanks, 
-Girija
