### ISSUE TITLE
Eclipse offline installation

### ISSUE THREAD

**Issue by GBMM01** [cucumber/cucumber-eclipse#224]
Is there an offline installation available?  The only one I can find is mrpotes. Which is missing a majority of the plugin. I need to install for all users. 

EDIT:Found Snapshot.

**Comment by girijant** [comment]
@GBMM01,
@nizamuddinj,
Cucumber-Eclipse plugin is alredy published as a Zip file which can be downloaded and installed **offline** from your local system.

Please download the plugin-zip(cucumber-eclipse-plugin-0.0.19-SNAPSHOT.zip) from the latest version(0.0.19-SNAPSHOT) directory of below url:

https://github.com/cucumber/cucumber-eclipse/tree/master/cucumber.eclipse.download/download
Also refer our Plugin-Download/Installation-Wiki for detail information.

**Comment by girijant** [comment]
@GBMM01,
Have you ever tried with above solution? Please confirm. I'm awaiting your response, else i would like to close this issue.

Thanks,
-Girija

**Comment by GBMM01** [comment]
I have, although it works, the version of Eclipse Neon is missing some dependencies of cucumber. Since cucumber needs to be installed under the users profile I am unable to get the dependencies installed.

**Comment by girijant** [comment]
@GBMM01,
As per my understand Cucumber-eclipse plugin installation does not depends on any user/dependency. It can be directly installed on any Eclipse-IDE version wothout considering any user/dependency. Please clarify your points in order to debug your issue.
It seems some issue with your eclipse environment. Points needs to be considered while installing new cucumber-eclipse plugin:
- After installing plugin, eclipse-ide must be restared.
- Older plugin version needs to be properly removed/uninstalled from your eclipse, please refer wiki link : https://github.com/cucumber/cucumber-eclipse/wiki/Uninstall-the-older-version-of-cucumber-eclipse-plugin
- For offline instalaltion, please refer wiki link: https://github.com/cucumber/cucumber-eclipse/wiki/Download-and-Install-Plugin-From-Zip

**Comment by GBMM01** [comment]
There are a couple folders that are created under the user profile tagged .eclipse which contain configurations for that user. Plug ins seem to be user based.

**Comment by girijant** [comment]
It seems you installed eclipse using installer. Can you please try with eclipse.zip bundle. Extract eclipse zip. Launch eclipse IDE from Extracted zip.  Then install plugin. 

Thanks, 
Girija

**Comment by girijant** [comment]
Closing this ticket.

**Comment by Akhilkr96** [comment]
plz share offline cucmber pulgin link for eclipse

**Comment by ShivakumarRH** [comment]
**For offline installation, please refer wiki link:**  is no active any more..
Please share active link..
