### ISSUE TITLE
Editor keeps auto-scrolling to the left margin

### ISSUE THREAD

**Issue by mikejramsey56** [cucumber/cucumber-eclipse#236]
Not sure if this is related to folding or not, but when editing a feature file my example line extends beyond the right border.  I scroll right to edit and the editor keeps auto scrolling back to the left margin.  This makes it very hard and time-consuming to edit.  I have to keep manually scrolling to the right.

**Comment by PyvesB** [comment]
Hello @mikejramsey56,

I am facing the same issue. I believe this is an Eclipse bug (see [Bug 321189](https://bugs.eclipse.org/bugs/show_bug.cgi?id=321189), but I'm unsure whether an easy workaround could be implemented in Cucumber Eclipse.

Cheers,

Pyves

**Comment by Flaburgan** [comment]
I do have the same problem too.

**Comment by girijant** [comment]
@Flaburgan, @PyvesB, @mikejramsey56,

From my ecllipse Version: Mars.2 (4.5.2),Build id: M20160212-1500 with instaleld Cucumber-plugin version 0.0.21, by default '**Enable Folding'** is ticked i.e. observed from **Preference>General>Editors>Structured Text Editors**.
 Now editing step in a feature file which extends beyond the right border. I scroll right to edit, but not seeing any auto scrolling issue.

Please confirm this issue with proper steps, snapshots and error-log(if any) for better understanding.

Thanks,
-Girija

**Comment by PyvesB** [comment]
@girijant I did a bit of investigation in order to be able to reproduce this issue on a brand new Eclipse installation (4.7.2 in my case) and workspace, with Cucumber-plugin version 0.0.21 installed. 

It seems that in addition to having example lines extend beyond the right border, you also need to have a file extending vertically by a significant margin. I managed to reproduce the issue on both an OS X and a Windows environment using the attached feature file (which is basically a copy/paste of the default template to increase vertical and horizontal lenghts).

[test.txt](https://github.com/cucumber/cucumber-eclipse/files/1745281/test.txt)

Hope this helps!

**Comment by individual-it** [comment]
still happens for me with eclipse 4.10.0 and cucumber-eclipse snapshot 2019-03-12 11:00:03

**Comment by JeremyAlosio** [comment]
Still happening for me on 4.13.0 and Cucumber-Eclipse Snapshot v1.0.0.202001082311

**Comment by laeubi** [comment]
The editor was rewritten in the 2.x line please retest there if the issue still persits.

**Comment by PyvesB** [comment]
> The editor was rewritten in the 2.x line

What do you mean by "2.x line"? I'm using the latest snapshot from https://github.com/cucumber/cucumber-eclipse-update-site-snapshot with the Eclipse 2021-03 and can still reproduce the problem.

**Comment by laeubi** [comment]
@PyvesB See the cucumber6 branch, I'm currently working on preparing a dedicated update-site for this,

**Comment by PyvesB** [comment]
Okay, will happily test again when the new site is available. :)
