### ISSUE TITLE
Cannot complete the provisioning operation while installing Maven Integration for Eclipse

### ISSUE THREAD

**Issue by alice-0-kim** [cucumber/cucumber-eclipse#250]
Hi,

I failed to install Maven Integration for Eclipse due to the errors during the installation process.

Any help would be appreciated. Thank you.

![screen shot 2018-02-21 at 11 49 13 am](https://user-images.githubusercontent.com/28884850/36502055-9cebc7ca-16fd-11e8-90d9-e49db2582bf0.png)

**Comment by girijant** [comment]
@alice-0-kim,
It seems your eclipse already has m2e plugin, you are trying to reinstall m2e plugin again. Please check m2e plugin info from your eclipse plugin installation page.

Thanks, 
Girija

**Comment by alice-0-kim** [comment]
Hi @girijant,

Thanks for your suggestion. I looked into the installation page, but I wasn't sure if it's been installed.
Here's the screenshot of it:
![screen shot 2018-02-22 at 2 49 27 pm](https://user-images.githubusercontent.com/28884850/36568733-ed36eab0-17df-11e8-89d1-99eaa196e3b0.png)
![screen shot 2018-02-22 at 2 49 43 pm](https://user-images.githubusercontent.com/28884850/36568738-f07345e8-17df-11e8-956d-12c095059324.png)
I had a look at the configuration information, and there was a line under features category that says `org.eclipse.m2e.feature (1.0.0.20110607-2117) "Maven Integration for Eclipse"`. Again, any help would be appreciated.

Thank you.

**Comment by girijant** [comment]
@alice-0-kim,
Please find out by selecting Help > About Eclipse Platform >. From this dialog, click Plug-in Details to get a list of all installed plug-ins, along with vendor and version information. I hope you must have maven plugin i.e. m2e. If already installed no need to install it again. Just install maven in your system. Add it to your system environment variable. Point your maven settings.xml into your eclipse.Create a maven project. For better understanding just googled your problems. But this issue is not related to our cucumber-eclipse plugin.

Thanks,
Girija

**Comment by alice-0-kim** [comment]
Thanks for the suggestion! I'll close the issue now.

**Comment by sidduchittaragi** [comment]
> Thanks for the suggestion! I'll close the issue now.

Hi mam,,im also facing same problem..How did you solve it?

**Comment by sidduchittaragi** [comment]
Hi mam, Im also facing same problem.. Not able to download or update plugins. How to solve it ,please tell me..
