### ISSUE TITLE
cucumber feature file not working with java 10

### ISSUE THREAD

**Issue by Raji-Tester** [cucumber/cucumber-eclipse#268]
After comeup with this "Cucumber - Feature File - nothing shows up in editor #220"issue feature editer working  ,but i got another promblem to run feature file ,try to run feature "Run as " option but nothing happened ,console display the message "No consoles  to display this time  "please help me to salve the issue

**Comment by girijant** [comment]
@Raji-Tester,
Please share your problems with detail snap-shots along with Cucumber-Plugin, Eclipse and java version.

Thanks,
-Girija

**Comment by edgarechm** [comment]
I found out that the problem is compatibility with Java 10. After I updated my java from version 8 to 10, when opening a feature file, the Eclipse editor displays "empty". I can only open the file with the "text" editor.

I had to delete all Java from the computer and downgraded to Java 8, now the plug in is working.

**Comment by laeubi** [comment]
In 2.x it will be possible to configure the java versionu used to run a feature
