### ISSUE TITLE
F3 to goto StepDef is time consuming

### ISSUE THREAD

**Issue by imkev** [cucumber/cucumber-eclipse#273]
I have updated Eclipse from Neon to Photon (4.8.0), and the Cucumber-Eclipse Plugin I used is 0.0.22.201806032001, every time I clicked F3 on one step in feature file, it's really very time consuming to jump to the step in StepDef file.
The release date for Photon and Cucumber plugin looks like in the same month. Is Photon 4.8.0 officially supported yet or is there anyway to fix or bypass this issue?

**Comment by johny2000uwb** [comment]
I have add the settings, you can set the path for your steps. It helps.

**Comment by imkev** [comment]
Thank you Johny, could you pls. explain how to add such a setting or set the path?

**Comment by johny2000uwb** [comment]
Preference, Cucumber, There is a path for it.
![01](https://user-images.githubusercontent.com/17253582/42925863-e990bab2-8b2f-11e8-9bf5-d828a74c6132.png)

**Comment by imkev** [comment]
Thank you for the instruction Johny, I put 'com.xxx.am.stepdefn.persona' there, where the stepdefinition files or sub-packages there, but it does not work.

**Comment by tomaugs** [comment]
I did the same configuration and it is still long to match the glue.
(maybe a bit better with the specific package configuration but still longer than 0.0.20 version)

**Comment by qvdk** [comment]
Could you provide a sample to reproduce this issue please ?

The plugin uses the ASTParser with bindings enabled. This function is expensive and I suspect it to be the root cause of this time consuming.

I think the bindings are not used, and I disabled them in the patch bellow. Could you test if this patch provide any improvements ?

https://github.com/qvdk/cucumber-eclipse/tree/fix/f3_is_time_consuming

This seems to improve performance a bit for several samples, but I don't have a signicant sample to ensure this resolve this issue. Do you have one?

**Comment by qvdk** [comment]
After more investigations, the time consuming comes from too many stepdefinitions scans.
This issue is related to the #233 where the steps are not detected as expected. 
For both, there are an issue on cucumber builder which can be not correctly setup when the cucumber nature is configured.

The too much stepdefinitions scans are due to mix of StepDefinition scanner between the JDTStepDefinition from the editor plugin and the StepDefinitions from the jdt plugin. 
The first should not be defined in this plugin, since its is related to the JDT. This fact reduce the ability to add support of others languages step definitions scanner.

I finished this first rework. 

Now, I already have too many stepdefinitions scans. The current StepsBuilder supports only full build : all ressources are scanned, even if you only update the java file in the current editor.
Too avoid a complete scan in this case, the StepsBuilder should support incremental build and the jdt.StepDefinitions should update and report on partial scan.
