### ISSUE TITLE
Eclipse cucumber plugin is not able to find step definitions from another project

### ISSUE THREAD

**Issue by nddipiazza** [cucumber/cucumber-eclipse#399]
I have an eclipse workspace with 2 projects:

`shared-step-defs`
`main-test-project`

The `main-test-project` has a cucumber test with:

```
@CucumberOptions(
  glue = {"main.project.stepdefs", "shared.project.stepdefs"}
...
```

where `main.project.stepdefs` is in the `main-test-project`, and `shared.project.stepdefs` is in the `shared-step-defs` project.

The feature files are all in `main-test-project`.

Cucumber eclipse plugin is unable to resolve step definitions from the `shared-step-defs` project. It fails to find them and highlights them as errors.

Is this a bug? Or is this a feature request?

**Comment by Abdallah-Aleies** [comment]
I am going through the same issue, Have you found a solution by any chance?

**Comment by girijant** [comment]
@nddipiazza,
Could you please share your project details with the required steps and example, so that  I can look into the issue...

**Comment by nddipiazza** [comment]
@girijant  https://github.com/nddipiazza/cucumber-java-skeleton

**Comment by nddipiazza** [comment]
@girijant  @Abdallah-Aleies  I fixed it here https://github.com/cucumber/cucumber-eclipse/pull/411/files

Also, do not forget to Right click project and click `Configure -> Convert to cucumber project` for all projects that you want to be involved.

**Comment by brunpoern** [comment]
Hi, 
in our setup the plugin doesn't find step definitions in other projects even if this other project is on the classpath. So we have a project 'foo-test' which depends on 'foo-test-util' (Eclipse project dependency). Both projects contain step definitions but only the once in foo-test are found, i.e. in the same project as the feature files. 

Actually, I can see in the feature file that it has found the step definitions from the other project (I see the method name and line number in the hoover) but jumping to the step definition doesn't work. But as I understood from the comments above, it should work, right?

I already started to debug the plugin. I'm not an Eclipse plugin expert but I stumbled across the computeScope method in JavaStepDefinitionsProvider. There it uses IJavaSearchScope.APPLICATION_LIBRARIES as search scope which sounds like it doesn't include the project dependencies?!

So my questions are
- Should it work in general for project dependencies?
- If yes, could you probably point me to the right place in the code, where it should find the step definitions from the project dependencies so that I can further debug it.

When I debugged the StepHyperlinkDetector I could see that the StepDefinitionsRepository only contains the step definitions from the current project but not from the project dependencies.

I have activated the Cucumber plugin also for the other project and I could also verify in the debugger that it finds the step definitions in our 'foo-test-util' project. But it doesn't find them when searching for step definitions of the 'foo-test' project.

Any help is welcome! 
Andreas

**Comment by laeubi** [comment]
We are currently developing a new version of the cucumber-plugin with improved support for more recent cucumber versions, if you like try out the following update-site (please uninstall the old plugin before):
https://cucumber.github.io/cucumber-eclipse/update-site/main/

**Comment by nddipiazza** [comment]
Sorry we have migrated to IntelliJ so we are no longer using this plugin.
