### ISSUE TITLE
Scanning for step definitions is causing an error - Unable to CTRL-Click/F3 to Step Defs

### ISSUE THREAD

**Issue by osuser2018** [cucumber/cucumber-eclipse#412]
VERSION INFO:
Eclipse Version: 2018-09 (4.9.0)
Build id: 20180917-1800
Cucumber Eclipse Feature version:  0.0.23.201811220126
Cucumber Editor version:  0.7.6.201505100000
JBehave Editor version:  0.3.0.201212080341

Preface:
My project has been running fine and the CTRL-click has been working as well for about 18 months...until now.

The Problem:
When I open a feature file I see the gherkin getting flagged as not not having matching glue code:

![image](https://user-images.githubusercontent.com/39202294/84308034-d729b680-ab2b-11ea-9c55-7d91df4be5a6.png)

Then, I see the error popup:

![image](https://user-images.githubusercontent.com/39202294/84307400-d6445500-ab2a-11ea-89cd-b4fd6cdcb254.png)

On another machine, I have the same set-up (i.e., plugin versions) and I do NOT see these errors.  

On the system that does display the error, I inadvertently updated the cucumber plugin to the latest version and I think this action placed some setting which is causing this error.  With this new update for Cucumber-eclipse (V. 1.00.202005150629) I saw that the Tools -> Preferences -> Cucumber menu had changed from what I see on my other working machine.  I tooled around with those settings for awhile but not finding a solution except to uncheck everything so that the annoying warnings would be turned off.  

Then I decided to uninstall and reinstall eclipse....  I have gone as far as completely reinstalling the plugins equal to what the working machine has.  Amazingly though, this error still shows up.  This indicates that perhaps there is a file holding a setting which did not get erased when I reinstalled eclipse.

One other thing... When I right-click, pulling up the context menu on the feature file (on the machine Im having this problem), I see some new menu items which I do NOT see on the machine which actually works.  Here are the menu items:

![image](https://user-images.githubusercontent.com/39202294/84308664-e3624380-ab2c-11ea-9922-59655a1d3d3a.png)

My general project structure varies slightly from some conventions but it has runs perfectly ...its just that the gherkin and step defs are not being interpretted properly.

![image](https://user-images.githubusercontent.com/39202294/84309484-2ec92180-ab2e-11ea-91a9-f47cc898b7aa.png)

Some guidance on how to correct this would be greatly appreciated.  Thanks!

**Comment by laeubi** [comment]
Can you provide an eclipse log output or reproducer?

**Comment by hpavan** [comment]
I faced the same problem. After  some analysis, I have figured out the problem. The issue is that, when you install cucumber plugin via eclipse market place or  download site [https://cucumber.github.io/cucumber-eclipse/update-site/](url), it installs quite an older version of that plugin.
What you have to do is, install the cucumber plugin manually as done by @osuser2018 . However just by uninstalling the older plugin from eclipse doesn't work as, it doesn't delete the jar files of the plugin from **plugins** folder of eclipse. What you have to do is delete those jar files as well as entries from **artifact.xml**  file manually, present in the plugin folder. 
For reinstallation of the plugin, I followed the instructions mentioned in the link [https://github.com/cucumber/cucumber-eclipse/wiki/Download-and-Offline-Installation-Of-The-Plugin-From-Zip](url) to a T from **Workaround** section in that post.

Steps to follow in short:
1. Uninstall the current cucumber plugin from the eclipse.
2. Close the eclipse and follow the instructions from link [https://github.com/cucumber/cucumber-eclipse/wiki/Download-and-Offline-Installation-Of-The-Plugin-From-Zip](url) to delete the plugin jars and entries in **artifact.xml**. Check **Workaround** section from that post.
3. Download the latest cucumber plugin for link [https://github.com/cucumber/cucumber-eclipse/releases](url) and install it via manual option then, restart the eclipse.
4.  If required, keep old features, step definitions files in back up and delete them from the project. Create the same new files and copy paste the contents from back up files.

Hopefully, this will solve the problem for good. It worked like charm for me.

**Comment by laeubi** [comment]
@osuser2018 please report back if the issue persist with latest version.
